# Fancy indexing and index tricks

NumPy offers more indexing facilities than regular Python sequences. 

In addition to indexing by integers and slices, as we saw before, arrays can be indexed by arrays of integers and arrays of booleans.

In [1]:
import numpy as np

## Indexing with Arrays of Indices

- array : 1D or 2D 
- array of indices : 1D or 2D   

In [2]:
a = np.arange(12)**2  
i = np.array([1, 1, 3, 8, 5])  # an array of indices
a[i]

array([ 1,  1,  9, 64, 25])

In [3]:
j = np.array([[3, 4], [9, 7]])  # a bidimensional array of indices
a[j]

array([[ 9, 16],
       [81, 49]])

In [4]:
palette = np.array( [ [0,0,0],                # black
                       [255,0,0],              # red
                       [0,255,0],              # green
                       [0,0,255],              # blue
                       [255,255,255] ] )       # white
image = np.array( [ [ 0, 1, 2, 0 ],           # each value corresponds to a color in the palette
                     [ 0, 3, 4, 0 ]  ] )
palette[image]                            # the (2,4,3) color image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [5]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
i = np.array([[0, 1],
              [1, 2]])
j = np.array([[2, 1],
              [3, 3]])
a[i,j] # l = [i, j]; a[l]

array([[ 2,  5],
       [ 7, 11]])

In [7]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [8]:
a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [9]:
s = np.array([i, j])
a[s]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [10]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

## Indexing with boolean arraysm

When we index arrays with arrays of (integer) indices we are providing the list of indices to pick. 

With boolean indices the approach is different; we explicitly choose which items in the array we want and which ones we don’t.m

In [11]:
a = np.arange(12).reshape(3,4)
a[a > 4] 

array([ 5,  6,  7,  8,  9, 10, 11])

In [12]:
a[a > 4] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])